version: 0.2

phases:
  install:
    commands:
      - echo Installing NGINX
      - sudo yum update -y
      - sudo amazon-linux-extras install nginx1.12 -y
      - sudo systemctl enable nginx
      - sudo systemctl start nginx
  build:
    commands:
      - echo Build started on `date`
      - sudo cp index.html /usr/share/nginx/html/
  post_build:
    commands:
      - echo Configuring NGINX
artifacts:
  files:
    - /usr/share/nginx/html/index.html
